export const merantsData = {
  'stockId-20550702': [
    {
      scene: '水费燃气费 (缴费通)',
      wechat_merchant_id: '454601975',
    },
    {
      scene: '电费 (电网)',
      wechat_merchant_id: '1530234621',
    },
  ],
  'stockId-20552499': [
    {
      scene: 'Xiao 雄 mall (雄安新区)',
      wechat_merchant_id: '1615460750',
      store_info: [
        { scene: 'Xiao雄mall 博雅庭菜店', address: '雄安新区容东片区容德西路8、10号' },
        { scene: 'Xiao雄mall 杏秋苑菜店', address: '雄安新区容东片区容德东路8、10、12号' },
        { scene: 'Xiao雄mall 弘文花园菜店', address: '雄安新区容东片区弘文街55号' },
        { scene: '雄Mall优选 华望城店', address: '河北省保定市容城县容东华望城尚华街10/11/12号' },
        { scene: 'Xiao雄mall 尚德花园菜店', address: '雄安新区容东片区双文街11号' },
        { scene: 'Xiao雄mall 玉水园早餐店', address: '雄安新区容东片区悦容街21号' },
        { scene: 'Xiao雄mall 朝晖园菜店', address: '雄安新区容东片区龚庄路41号' },
        { scene: 'xiao雄mall福星苑早餐店', address: '雄安新区容东片区容德东路208号' },
        { scene: 'Xiao雄mall 玉水园菜店', address: '雄安新区容东片区悦容街17号' },
        { scene: 'Xiao雄mall 金源庭便利店', address: '雄安新区容东片区红莲街11号' },
        { scene: 'Xiao雄mall 红莲东园便利店NO.1', address: '雄安新区容东片区红莲街113号' },
        { scene: 'Xiao雄mall 兴贤庭便利店', address: '雄安新区容东片区八于街33号' },
        { scene: 'xiao雄mall长庆居菜店', address: '雄安新区雄东片区兴易路01号' },
        { scene: 'xiao雄mall花锦苑菜店', address: '雄安新区雄东片区同德四路21号' },
        { scene: 'xiao雄mall兰桨坊菜店', address: '雄安新区雄东片区学苑西路08号' },
        { scene: 'Xiao雄mall瑞康居便利店+菜店', address: '雄安新区雄东片区兴易路144号' },
        { scene: 'Xiao雄mall龙润东居菜店', address: '雄安新区雄东片区小步西街8号' },
        { scene: 'Xiao雄mall龙润中居便利店', address: '雄安新区雄东片区兴易路180号' },
        { scene: 'Xiao雄mall崇文西坊便利店', address: '雄安新区雄东片区涞济路179号' },
        { scene: 'Xiao雄mall小步南坊菜店', address: '雄安新区雄东片区涞济路188号' },
        { scene: 'Xiao雄mall龙台居便利店+早餐店', address: '雄安新区雄东片区兴易路208号' },
        { scene: 'Xiao雄mall自贸大厦咖啡厅', address: '雄安新区高新区综合管理服务中心619-004' },
        { scene: 'Xiao雄mall 临泉苑', address: '雄安新区容西片区龙泉西路6号' },
        { scene: 'Xiao雄mall 华淀西庭', address: '雄安新区容西片区金安北街70号、72号' },
        { scene: 'Xiao雄mall 仁和北园', address: '雄安新区容西片区津保大街16号' },
        { scene: 'Xiao雄mall 同福园便利店', address: '雄安新区容西片区文苑中路3号' },
        { scene: '雄Mall优选 中交启园店', address: '雄安新区启动区启园康乐北街23号' },
        { scene: 'Xiao雄mall云霞园便利店', address: '雄安新区启动区晨兴街4号' },
        {
          scene: 'Xiao雄mall 服务驿站 快餐店',
          address: '雄安新区启动区西里路1-6号(Xiao雄mall服务驿站内)',
        },
        {
          scene: 'Xiao雄mall 服务驿站 特色餐饮',
          address: '雄安新区启动区西里路1-1号)(Xiao雄mall服务驿站内)',
        },
        {
          scene: 'Xiao雄mall 服务驿站 综合超市',
          address: '雄安新区启动区西里路1-3号(Xiao雄mall服务驿站内)',
        },
        { scene: 'Xiao雄mall 中交启园博思居便利店', address: '雄安新区启动区中交启园博思居4号楼' },
        {
          scene: 'Xiao雄mall大学城便利店',
          address: '河北省雄安新区容城县起步区第五组团大学城配套一期燕赵大街与NA12路交汇处',
        },
      ],
    },
    {
      scene: '百乐百货便利店 (雄安新区)',
      wechat_merchant_id: ['402327689', '1588761551', '558689729', '558689730', '341086169'],
      store_info: [
        { store_code: '0001', scene: '容城豪丹路民大附中店' },
        { store_code: '0002', scene: '容城新容花园店' },
        { store_code: '0003', scene: '容城奥威路工商银行店' },
        { store_code: '0008', scene: '容城县政府对面店' },
        { store_code: '0009', scene: '容城豪丹路新北花园店' },
        { store_code: '0010', scene: '容城金容南街店' },
        { store_code: '0015', scene: '容城县医院对面店' },
        { store_code: '0016', scene: '容城罗萨大街店' },
        { store_code: '0017', scene: '容城祥和新区店' },
        { store_code: '0018', scene: '容城朝实附小店' },
        { store_code: '0019', scene: '容城板正南大街店' },
        { store_code: '0020', scene: '容城长途汽车站店' },
        { store_code: '0021', scene: '容城永贵南大街农行店' },
        { store_code: '0022', scene: '容城工会小区店' },
        { store_code: '0023', scene: '安新县中医院店' },
        { store_code: '0024', scene: '安新永安大街强大宾馆店' },
        { store_code: '0025', scene: '安新县医院对面店' },
        { store_code: '0026', scene: '安新雁翎东路店' },
        { store_code: '0027', scene: '容城板正北大街鑫源小区店' },
        { store_code: '0028', scene: '安新永安大街店' },
        { store_code: '0029', scene: '安新育才西路店' },
        { store_code: '0030', scene: '容城容美路店' },
        { store_code: '0031', scene: '安新雁翎西路店' },
        { store_code: '0033', scene: '白沟天成嘉园店' },
        { store_code: '0034', scene: '雄县文昌大街店' },
        { store_code: '0035', scene: '白沟五一路凤凰城店' },
        { store_code: '0036', scene: '白沟团结路店' },
        { store_code: '0040', scene: '白沟五一路物流中心店' },
        { store_code: '0042', scene: '雄县绿港新城店' },
        { store_code: '0045', scene: '徐水华龙路欧韵华庭店' },
        { store_code: '0046', scene: '徐水广场店' },
        { store_code: '0047', scene: '定兴华建路裕兴园店' },
        { store_code: '0048', scene: '定兴玉路华庭店' },
        { store_code: '0049', scene: '定兴云峰妇产医院店' },
        { store_code: '0051', scene: '徐水振兴中路店' },
        { store_code: '0053', scene: '定兴国泰北街燕城隽府店' },
        { store_code: '0057', scene: '安新建设大街温泉花园店' },
        { store_code: '0058', scene: '容城东牛店' },
        { store_code: '0059', scene: '容东文营路尚德花园店' },
        { store_code: '0060', scene: '容东容德东路闻梅苑店' },
        { store_code: '0061', scene: '容东文营路居贤花园店' },
        { store_code: '0062', scene: '容东红莲街明珠园店' },
        { store_code: '0063', scene: '容东红莲街红莲中园店' },
        { store_code: '0067', scene: '容东金湖东路临波庭店' },
        { store_code: '0068', scene: '容东金湖西路店' },
        { store_code: '0071', scene: '容东兴贤路东店' },
        { store_code: '0072', scene: '雄东兴易路店' },
        { store_code: '0074', scene: '雄东同德四路店' },
        { store_code: '0075', scene: '容西志学北街店' },
        { store_code: '0077', scene: '容西福泉北院店' },
        { store_code: '0079', scene: '安新北大街店' },
        { store_code: '0080', scene: '安新育才花园小区店' },
        { store_code: '0081', scene: '安新永安大街京新风景园店' },
        { store_code: '0082', scene: '安新雁翎路湿地华城店' },
        { store_code: '0083', scene: '安新雁翎路交通局店' },
        { store_code: '0084', scene: '容东红莲街红莲东园店' },
      ],
    },
    {
      scene: '雄安进口商品展销中心',
      wechat_merchant_id: '1708796346',
    },
  ],
  'stockId-20553080': [
    {
      scene: '食堂充值 (C5、B5、B7)',
      wechat_merchant_id: '714774255',
    },
    {
      scene: '定安社区食堂',
    },
    {
      scene: '南文营社区食堂',
    },
  ],
}
