/**
 * API服务入口文件
 * 导出所有API服务
 */

// 请求模块
export { default as request, login, get, post, put, del, deleteMethod, APP_CONFIG } from './request'

// 各个服务模块
export { default as ActivityService } from './activityService'
export { default as AddressService } from './addressService'
export { default as AdvanceSellService } from './advanceSellService'
export { default as BackCashService } from './backCashService'
export { default as BankCardService } from './backCashService'
export { default as BannerService } from './bannerService'
export { default as BargainService } from './bargainService'
export { default as CommentService } from './commentService'
export { default as CouponService } from './couponService'
export { default as CreditCardService } from './creditCardService'
export { default as CycleService } from './cycleService'
export { default as DistributionService } from './distributionService'
export { default as FeedbackService } from './feedbackService'
export { default as FloristService } from './floristService'
export { default as GiftCardService } from './giftCardService'
export { default as HelpActivityService } from './helpActivityService'
export { default as HomepageService } from './homepageService'
export { default as InvoiceService } from './invoiceService'
export { default as LiveRoomService } from './liveRoomService'
export { default as LotteryService } from './lotteryService'
export { default as MemberService } from './memberService'
export { default as NewGoodsService } from './newGoodsService'
export { default as NewmbrActivityService } from './newmbrActivityService'
export { default as OfflineOrderService } from './offlineOrderService'
export { default as OrderService } from './orderService'
export { default as PackagingService } from './packagingService'
export { default as PennyService } from './pennyService'
export { default as ProductService } from './productService'
export { default as PromotionService } from './promotionService'
export { default as RaffleService } from './raffleService'
export { default as RechargeService } from './rechargeService'
export { default as RecommendService } from './recommendService'
export { default as RedPacketService } from './redPacketService'
export { default as SalesclerkViewingService } from './salesclerkViewingService'
export { default as ScoreProductService } from './scoreProductService'
export { default as SearchService } from './searchService'
export { default as SeckillService } from './seckillService'
export { default as SharePicturesService } from './sharePicturesService'
export { default as ShopcartService } from './shopcartService'
export { default as SmsService } from './smsService'
export { default as SolitaireService } from './solitaireService'
export { default as StoreService } from './storeService'
export { default as SubscribeService } from './subscribeService'
export { default as SystemService } from './systemService'
export { default as TeamBuyService } from './teamBuyService'
export { default as Treaty } from './treaty'
export { default as UserService } from './userService'
export { default as WelfarePlanService } from './welfarePlanService'
export { default as WisdomService } from './wisdomService'
export { default as WxaExperienceService } from './wxaExperienceService'
export { default as WxaUserService } from './wxaUserService'

// 工具模块
export { default as utils } from '../utils/utils'
export { default as auth } from '../utils/auth'
export { default as NAVPAGE } from '../utils/navPage'